<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CEK NO 20</name>
   <tag></tag>
   <elementGuidId>0dc77a51-91ea-4462-9e00-aa920a38c4e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvTermCondition_cbChecked_19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvTermCondition_cbChecked_19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvTermCondition_cbChecked_19</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8428aa78-1dcb-431a-9d6d-d599340ece58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTermCondition_cbChecked_19</value>
      <webElementGuid>ee5e1734-911c-4a0b-a171-2f2dd01f152f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>396963d2-ade7-4d44-b4d7-78c2fc96f968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvTermCondition$ctl21$cbChecked</value>
      <webElementGuid>a4d538ba-99ea-4bdf-94ad-70d4de0d409c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvTermCondition$ctl21$cbChecked\',\'\')', 0)</value>
      <webElementGuid>4d5b5923-f441-4007-b076-1bec141884a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvTermCondition_cbChecked_19&quot;)</value>
      <webElementGuid>4e7c87f7-12d9-4bc4-bf9a-67a6e20b6374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Term condition/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>b74ed939-2869-449f-a77f-d9e9b0cb966f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvTermCondition_cbChecked_19']</value>
      <webElementGuid>e5e63379-04c7-4203-abb0-2589db89363d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTermCondition']/tbody/tr[21]/td[5]/input</value>
      <webElementGuid>bd3e31fc-41e6-4e4d-8f37-1925b5205e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[21]/td[5]/input</value>
      <webElementGuid>83e57ed5-b6f6-43bb-8420-6dd5538eeb71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvTermCondition_cbChecked_19' and @type = 'checkbox' and @name = 'gvTermCondition$ctl21$cbChecked']</value>
      <webElementGuid>d4e55820-c539-4a83-b9ff-e12c14945680</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
