<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NO 20</name>
   <tag></tag>
   <elementGuidId>efb61f53-a86c-4253-9610-eefe3d70df14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvTermCondition_lblIsMandatory_19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='gvTermCondition_lblIsMandatory_19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvTermCondition_lblIsMandatory_19</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f3e2d602-4ac2-413a-a2e8-ee16ea3c5c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTermCondition_lblIsMandatory_19</value>
      <webElementGuid>0ececb9c-9edd-4c14-b97b-4a079a83586b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>77352d7d-9efa-47e7-a217-2c4f7167f14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvTermCondition_lblIsMandatory_19&quot;)</value>
      <webElementGuid>0c2ba625-e9df-460f-8b9d-7f361e9905ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Term condition/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>029bb709-e702-4c0d-a0e4-3e7d6d0e897c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='gvTermCondition_lblIsMandatory_19']</value>
      <webElementGuid>4f10467e-578b-4417-a3f6-73e926046ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTermCondition']/tbody/tr[21]/td[4]/span</value>
      <webElementGuid>6e55c532-ec9a-4fe2-96ab-232410d988b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GLV'])[2]/following::span[1]</value>
      <webElementGuid>dc7bb73f-cd94-458f-8f00-009169dd4f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SURAT PERNYATAAN BERSAMA BPKB (SP-BPKB)'])[1]/following::span[2]</value>
      <webElementGuid>f251cf4e-1b37-4797-9297-cb65c948b456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid Date'])[39]/preceding::span[2]</value>
      <webElementGuid>a22ff966-2e27-477c-a7a1-ebc17272b711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[39]/preceding::span[3]</value>
      <webElementGuid>c852972e-189b-4e09-b40b-6c7cc2a1984e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[21]/td[4]/span</value>
      <webElementGuid>a8b2bfff-9071-4633-8fc7-b4756882567f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'gvTermCondition_lblIsMandatory_19' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>3f62329f-f0d1-4fa4-a2ed-578da831e6ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
