<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NO 36</name>
   <tag></tag>
   <elementGuidId>871df521-61ed-48eb-a19f-43734fb602bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvTermCondition_lblIsMandatory_35</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='gvTermCondition_lblIsMandatory_35']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#gvTermCondition_lblIsMandatory_35</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>173919d1-2f05-4b64-962c-1057e1c9c1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTermCondition_lblIsMandatory_35</value>
      <webElementGuid>f2d93511-8a27-4529-8bf1-ede683401419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>c9f9bd43-8cee-40cf-ba84-b236106d9b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvTermCondition_lblIsMandatory_35&quot;)</value>
      <webElementGuid>46a15864-e572-4631-8fdc-7c28e3c2a021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Tab Term condition/Page_New Confins - Main/iframe_Term  Condition_appForm</value>
      <webElementGuid>0f5504c8-dcea-4f3d-bd2f-7fe69c6e259f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='gvTermCondition_lblIsMandatory_35']</value>
      <webElementGuid>2d7e6026-7663-436b-a496-54a2b9928771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTermCondition']/tbody/tr[37]/td[4]/span</value>
      <webElementGuid>eb8bced0-f721-4fc7-a200-0e3ed0f28a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GLV'])[18]/following::span[1]</value>
      <webElementGuid>4feb999f-0e43-4906-b04c-b75f07044eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SURAT PERSETUJUAN BLOKIR BPKB'])[1]/following::span[2]</value>
      <webElementGuid>a2600d4c-af68-4c61-8f1b-daecc17b6069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid Date'])[71]/preceding::span[2]</value>
      <webElementGuid>1b5c28b5-5c78-4608-b511-f8a56cb8dc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[71]/preceding::span[3]</value>
      <webElementGuid>d186d35b-0e7b-4fd1-8c5b-e5d8b754896c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[37]/td[4]/span</value>
      <webElementGuid>c65978b1-7b54-4901-8b1f-b436544af09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'gvTermCondition_lblIsMandatory_35' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>70a74bba-d048-4fcc-8c9d-392a6b31b3f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
